### ISSUE TITLE
vec-push-ref code and CFG do not match

### ISSUE THREAD

**Issue by RalfJung** [nikomatsakis/nll-rfc#12]
The code has the `use` in the `else`, while the CFG has it after the conditional merges again. The CFG seems to cover the more interesting case.

**Comment by nikomatsakis** [comment]
I think I aligned these, but perhaps not in the way you wanted. (That is, I made the CFG match the code.) It might be interesting to just work out both of them in the RFC.

**Comment by nikomatsakis** [comment]
I'm gonna' close, in any case. =)
