### ISSUE TITLE
[borrowck] discriminant accesses

### ISSUE THREAD

**Issue by arielb1** [nikomatsakis/nll-rfc#39]
Enum discriminants can be accessed in today's Rust without doing a read of all the interior of the enum:
```Rust
fn main() {
    let mut t = Some(0);
    let y = if let Some(ref mut y) = t {
        y
    } else {
        panic!();
    };
    
    if let Some(_) = t {
        println!("{}", y);
    }
}
```

I think the smartest way to handle this is to treat discriminants as their own separate field. This might warrant a note in the RFC.

Sorry for being tedious here - I am trying to use the borrowck part of this RFC as a specification to check against while reviewing MIR borrowck.

**Comment by nikomatsakis** [comment]
This is a very good point. I agree with the idea of them being a kind of field.
