### ISSUE TITLE
Consider iterating backwards

### ISSUE THREAD

**Issue by Darksonn** [nikomatsakis/nll-rfc#7]
Consider the following simple code:

    A/0: let a = vec![1,2,3];
    A/1: let b = &a;
    A/2: let c = &b;
    A/3: let d = &c;
    A/4: let e = &d;
    A/5: let f = &e;
    A/6: let g = &f;
    A/7: let h = &g;
    A/8: let i = &h;
    A/9: let j = &i;
    A/10: let k = &j;
    A/11: let l = &k;
    A/12: let m = &l;
    A/13: println!("{}", m[0]);

As far as I understand, the above code produces the following constraints:

    ('a: 'b) @ A/1
    ('b: 'c) @ A/2
    ('c: 'd) @ A/3
    ('d: 'e) @ A/4
    ('e: 'f) @ A/5
    ('f: 'g) @ A/6
    ('g: 'h) @ A/7
    ('h: 'i) @ A/8
    ('i: 'j) @ A/9
    ('j: 'k) @ A/10
    ('k: 'l) @ A/11
    ('l: 'm) @ A/12
    ('m: {A/13}) @ A/13

Now let's see what happens with this algorithm.

1. In the first iteration, all lifetimes start out empty, and after the iteration 'm contains {A/13}
2. After the second iteration we change 'l to {A/12, A/13}
3. After the third iteration we change 'k to {A/11, A/12, A/13}
4. and so on

This is O(n^2). I'm not quite sure what kind of constraints can be formed from actual code, but if they happen to always form a DAG, doing a single pass of the iteration backwards would suffice. (it would still be O(n^2) since on the above code it outputs a collection of size O(n^2), but it would be faster)

**Comment by nikomatsakis** [comment]
I'm going to close this issue as a kind of implementation detail (unless you think there is something here that *must* be specified in the RFC itself -- if so, let me know).
